Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/VariableName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false
